### PR TITLE
expose max-bagfile-size for recording command line verb

### PR DESCRIPTION
**Pull request by Karsten1987**
title should be self explanatory.

Signed-off-by: Karsten Knese <karsten@openrobotics.org>

### CODE REVIEW

**Comment by prajakta-gokhale** [comment]
These changes are mostly the same as this CLI changes [commit](https://github.com/aws-ros-dev/rosbag2/commit/5265687a6a2cdd8c315f3eb33463df4f10eb6f3d). Should I open a PR with that commit on rosbag2/master instead of moving ahead with this PR?

**Comment by Karsten1987** [comment]
It's essentially your call. I wasn't aware of that commit. So I believe it makes sense to add this commit to the open PR tackling the changes in the writer implementation as it's part of the same feature.

**Comment by prajakta-gokhale** [comment]
I'd prefer creating a PR upstream since that's where we want the changes eventually.

>  I wasn't aware of that commit.

We intentionally kept the CLI changes for the last so the functionality isn't exposed to users before it is fully functional. With that in mind, I thought it better to make the CLI changes a separate PR instead of adding it to the open Writer PR (https://github.com/ros2/rosbag2/pull/185) so it can be reviewed and merged independently.

Since you're the one reviewing it I'd defer that decision to you.

**Comment by Karsten1987** [comment]
a follow up PR seems fine to me. I actually just added the commit in this PR for me to easily test the new functionality until the tests are available as discussed [here](https://github.com/ros2/rosbag2/pull/185#issuecomment-553183452)

**Comment by prajakta-gokhale** [comment]
Opened https://github.com/ros2/rosbag2/pull/203 for this.

**Pull request closed without merging**
