### PR TITLE
Create new interface for SequentialReader

### PR DESCRIPTION
**Pull request by Karsten1987**
@prajakta-gokhale @piraka9011 

That's a rebased version of https://github.com/ros2/rosbag2/pull/191 just in case to accelerate the set of PRs for splitting.

### CODE REVIEW

**Review by prajakta-gokhale — APPROVED** [review]

**Comment by prajakta-gokhale** [comment]
Thanks for the contribution!

**Comment by Karsten1987** [comment]
@prajakta-gokhale you have to update your `reader-interfaces` branch with the aws master (latest) in order to get https://github.com/ros2/rosbag2/pull/191 in a mergeable state.

**Comment by Karsten1987** [comment]
in the meantime, I am currently working on a follow up PR for having the same interface structures for the writer api.

**Comment by prajakta-gokhale** [comment]
Working on updating the `reader-interface` branch. Let me know if I can help with the `Writer` changes.

**Pull request merged**
